export { HomePage } from './HomePage';
export { HistoryPage } from './HistoryPage';
export { ClosetPage } from './ClosetPage';
export { SettingsPage } from './SettingsPage';
export { LogOutfitPage } from './LogOutfitPage';
export { LoginPage } from './LoginPage';
export { SignupPage } from './SignupPage';
export { StartPage } from './StartPage';
export { LogItemPage } from './LogItemPage';